python -m nmt.nmt \
--src=en --tgt=zh \
--attention=scaled_luong \
--vocab_prefix=nmt_zh/vocab \
--train_prefix=nmt_zh/train \
--dev_prefix=nmt_zh/dev \
--test_prefix=nmt_zh/test \
--out_dir=nmt_model_zh \
--step_per_stats=100 \
--num_train_steps=1200 \
--num_layers 3 \
--num_units 256 \
--dropout 0.2 \
--metrics bleu;